# Generated by Django 3.2 on 2022-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0008_modelperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=250)),
                ('model_ver', models.CharField(max_length=10)),
                ('model_selected', models.BooleanField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('model', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='model_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
