# Generated by Django 3.2 on 2022-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0009_auto_20221122_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperformance',
            name='acc',
            field=models.FloatField(default=0.0),
        ),
    ]
